In [1]:
def saludar_usuario ():
    print('Hola Mundo')

In [2]:
saludar_usuario()

Hola Mundo


In [3]:
def suma(a,b):
    return a + b

suma(10,20)

30

In [4]:
?

In [5]:
suma?

In [6]:
# arreglos
import numpy as np

In [7]:
a = np.array([1,2,2,3,4,5,6,7,8,9,9,9,9,10])

In [8]:
a

array([ 1,  2,  2,  3,  4,  5,  6,  7,  8,  9,  9,  9,  9, 10])

In [9]:
type(a)


numpy.ndarray

In [10]:
a.size

14

In [11]:
a.ndim #dimension

1

In [12]:
a.dtype # tipo de dato

dtype('int32')

In [13]:
a.shape # cantidad de elementos por dimensión

(14,)

In [14]:
a-10

array([-9, -8, -8, -7, -6, -5, -4, -3, -2, -1, -1, -1, -1,  0])

In [15]:
b = np.array([1,2,2,3,4,5,6,7,8,9,9,9,9,10], dtype=float)
b

array([ 1.,  2.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.,  9.,  9.,  9.,
       10.])

In [16]:
b = np.array([1,2,2,3,4,5,6,7,8,9,9,9,9,10], dtype=str)
b

array(['1', '2', '2', '3', '4', '5', '6', '7', '8', '9', '9', '9', '9',
       '10'], dtype='<U2')

In [17]:
b = np.array([1,2,2,3,4,5,6,7,8,9,9,9,9,10], dtype=bool)
b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [18]:
b = np.array([1,2,2,3,4,5,6,0,8,9,9,9,9,10], dtype=bool)
b

array([ True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True])

In [19]:
b = np.array([1,2,2,3,4,5,6,7,8,9,9,9,9,10], dtype=np.complex)
b

array([ 1.+0.j,  2.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j,
        7.+0.j,  8.+0.j,  9.+0.j,  9.+0.j,  9.+0.j,  9.+0.j, 10.+0.j])

In [20]:
np.arange(0,20) # arreglo donde queremos iniciar y terminar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [21]:
np.zeros(10) # arreglode ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros(10, dtype=int) # arreglode ceros int

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
np.ones(10, dtype=int) # arreglode unos int

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [31]:
np.empty(11) # arreglode unos int

array([            nan, 0.00000000e+000, 9.30460058e-312, 2.02369289e-320,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000])

In [32]:
np.random.randint(0,100,50) #arreglos con numeros enteros aleatorios, rango inicial, rango final, numero de datos

array([ 4,  5, 79, 11, 76, 76, 30, 65, 91, 39, 81,  8, 98, 63, 76, 79, 72,
       55, 86, 12, 74, 36,  5, 58, 49, 85, 21,  8, 72, 14,  7, 98,  0, 24,
       10, 64,  2, 53, 96, 46, 48, 16, 70, 52, 19, 15, 63, 16, 39, 87])

In [33]:
a[1] # primer elemento izquierda a derecha

2

In [34]:
a[-1] # ultimo elemento derecha a izquierda

10

In [35]:
a[0:5] # inicio:final:candtidad saltos

array([1, 2, 2, 3, 4])

In [36]:
a[0:5:2] # inicio:final:candtidad saltos

array([1, 2, 4])

In [37]:
a[:5] # inicio:final:candtidad saltos

array([1, 2, 2, 3, 4])

In [38]:
a[0:] # inicio:final:candtidad saltos

array([ 1,  2,  2,  3,  4,  5,  6,  7,  8,  9,  9,  9,  9, 10])

In [39]:
a[:5:2] # inicio:final:candtidad saltos

array([1, 2, 4])

In [41]:
a[[2,4,7]] # subarreglos

array([2, 4, 7])

In [54]:
a = np.random.randint(0,10,20)

def sumaextrema(valor):
    return (valor)**2

sumaextrema(3)


for valor in a:
    sumaextrema(valor)
    print(sumaextrema(valor))

    vector = np.vectorize(sumaextrema)

vector(a)
    

25
1
16
0
16
1
9
64
16
0
0
1
25
4
0
0
16
16
81
25


array([25,  1, 16,  0, 16,  1,  9, 64, 16,  0,  0,  1, 25,  4,  0,  0, 16,
       16, 81, 25])

In [55]:
a.copy()

array([5, 1, 4, 0, 4, 1, 3, 8, 4, 0, 0, 1, 5, 2, 0, 0, 4, 4, 9, 5])

In [56]:
b = a.copy()

In [62]:
id(a)


1883320702736

In [63]:
id(b)

1883320548688

In [64]:
a is b # validar si son iguales

False

In [65]:
a.view()

array([5, 1, 4, 0, 4, 1, 3, 8, 4, 0, 0, 1, 5, 2, 0, 0, 4, 4, 9, 5])

In [66]:
b=a.view()

In [67]:
id(a)

1883320702736

In [68]:
id(b)

1883320698080

In [70]:
a is b # las vistas modifican las dos, con copia solo modifica uno

False

In [73]:
c = a[:]
c

array([5, 1, 4, 0, 4, 1, 3, 8, 4, 0, 0, 1, 5, 2, 0, 0, 4, 4, 9, 5])

In [79]:
D = np.array([
    np.random.randint(1,500,10),
    [1,2,3,4,5,6,7,8,9,10],
    [0,50,10,50,50,60,70,80,90,10]
])

D

array([[443, 419,  61, 127, 492,  80, 133,  21, 105,  64],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  0,  50,  10,  50,  50,  60,  70,  80,  90,  10]])

In [80]:
D.ndim#concer las dimensiones

2

In [81]:
D.shape # filas y columnas

(3, 10)

In [82]:
D[1][1]

2

In [85]:
D[0][9]

64

In [86]:
D[1,:3] # obtener 

array([1, 2, 3])

In [87]:
D[1,3:] # obtener de

array([ 4,  5,  6,  7,  8,  9, 10])

In [88]:
D[:,3] # obtener de

array([127,   4,  50])

In [90]:
D.std() # concoer la desviacion estandar del arreglo

129.24094638396232

In [91]:
D.sum() # suma de todo el arreglo

2470

In [92]:
D.min()


0

In [93]:
D.max()

492

In [94]:
D.mean()

82.33333333333333

In [95]:
D[1].sum()

55

In [96]:
D[0].sum()

1945

In [97]:
D[0].min()

21

In [98]:
D[0].mean()

194.5

In [99]:
D[:,0].mean() # promedio de la primera columna

148.0

In [101]:
D[:,1].mean() # promedio de la segunda columna

157.0

In [102]:
D.T #transponer las filas por columnas

array([[443,   1,   0],
       [419,   2,  50],
       [ 61,   3,  10],
       [127,   4,  50],
       [492,   5,  50],
       [ 80,   6,  60],
       [133,   7,  70],
       [ 21,   8,  80],
       [105,   9,  90],
       [ 64,  10,  10]])

In [103]:
 a>50

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [104]:
a>1

array([ True, False,  True, False,  True, False,  True,  True,  True,
       False, False, False,  True,  True, False, False,  True,  True,
        True,  True])

In [105]:
a[a>1]

array([5, 4, 4, 3, 8, 4, 5, 2, 4, 4, 9, 5])

In [109]:
a[(a>1) & (a<8)] # and

array([5, 4, 4, 3, 4, 5, 2, 4, 4, 5])

In [113]:
a[(a==1) | (a<6)] # or

array([5, 1, 4, 0, 4, 1, 3, 4, 0, 0, 1, 5, 2, 0, 0, 4, 4, 5])

In [114]:
np.all(a>3)# si todos los elementos son mayores que 3

False

In [116]:
np.all(a>=0)# si todos los elementos son mayores que 3

True

In [118]:
np.any((a>=0) & (a<=100))# si todos los elementos son mayores que 0 y menores que 100

True

In [120]:
np.any((a>=0) & (a<=6))# si todos los elementos son mayores que 0 y menores que 6

True

In [121]:
np.any(a<=6) # si algun numero que sea por lo menos menor a 6

True

In [122]:
np.where(
a > 7,
    'super',
    'paila'
)

array(['paila', 'paila', 'paila', 'paila', 'paila', 'paila', 'paila',
       'super', 'paila', 'paila', 'paila', 'paila', 'paila', 'paila',
       'paila', 'paila', 'paila', 'paila', 'super', 'paila'], dtype='<U5')

In [130]:
condiciones = [
    (a == 8),
    ((a == 7) | (a ==6)),
    (a == 5),
    (a <5)
]

opciones = [
    
    'ok',
    'ok ok ',
    'ok ok ok',
    'super ok',
]

In [131]:
np.select(condiciones, opciones)

array(['ok ok ok', 'super ok', 'super ok', 'super ok', 'super ok',
       'super ok', 'super ok', 'ok', 'super ok', 'super ok', 'super ok',
       'super ok', 'ok ok ok', 'super ok', 'super ok', 'super ok',
       'super ok', 'super ok', '0', 'ok ok ok'], dtype='<U11')

In [129]:
a

array([5, 1, 4, 0, 4, 1, 3, 8, 4, 0, 0, 1, 5, 2, 0, 0, 4, 4, 9, 5])